# Generated by Django 2.2.7 on 2019-12-08 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessLvl',
            fields=[
                ('accessID', models.AutoField(primary_key=True, serialize=False)),
                ('accessName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='end_user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('faceImgDir', models.FilePathField()),
                ('accessID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinel.accessLvl')),
            ],
        ),
        migrations.CreateModel(
            name='activity_log',
            fields=[
                ('activityID', models.AutoField(primary_key=True, serialize=False)),
                ('firstSeen', models.DateTimeField(default=datetime.datetime.now)),
                ('lastSeen', models.DateTimeField()),
                ('faceCaptureDir', models.FilePathField()),
                ('clipDir', models.FilePathField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinel.end_user')),
            ],
        ),
    ]
