# Generated by Django 2.2.7 on 2019-12-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notifID', models.AutoField(primary_key=True, serialize=False)),
                ('notifType', models.CharField(max_length=20)),
                ('notifDetails', models.CharField(max_length=300)),
                ('notifImgDir', models.FilePathField()),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='notification_recipients',
            fields=[
                ('recipientID', models.AutoField(primary_key=True, serialize=False)),
                ('accessID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinel.accessLvl')),
                ('notifID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinel.notification')),
            ],
        ),
    ]
