# Generated by Django 2.2.7 on 2019-12-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0002_notification_notification_recipients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accessLvl',
            new_name='access_lvl',
        ),
    ]
