# Generated by Django 2.2.7 on 2019-12-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_auto_20191209_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notification_recipients',
            new_name='notification_recipient',
        ),
    ]
