# Generated by Django 2.2.7 on 2019-12-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0005_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='clipDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs'),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='faceCaptureDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs'),
        ),
        migrations.AlterField(
            model_name='audit_log',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sentinel.end_user'),
        ),
        migrations.AlterField(
            model_name='end_user',
            name='faceImgDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifImgDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs'),
        ),
    ]
