# Generated by Django 2.2.7 on 2019-12-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0006_auto_20191213_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_user',
            name='faceImgDir',
            field=models.FileField(blank=True, upload_to='C:\\Users\\ernes\\Python\\fileDirs'),
        ),
    ]
