# Generated by Django 2.2 on 2020-01-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0007_auto_20191213_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_user',
            name='faceImgDir',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True),
        ),
    ]
