# Generated by Django 2.2 on 2020-01-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0008_auto_20200112_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_user',
            name='faceImgDir',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, path='C:\\Users\\ernes\\Python\\fileDirs'),
        ),
    ]
