# Generated by Django 2.2 on 2020-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0009_auto_20200112_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='clipDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs/users'),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='faceCaptureDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs/users'),
        ),
        migrations.AlterField(
            model_name='end_user',
            name='faceImgDir',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, path='C:\\Users\\ernes\\Python\\fileDirs/users'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifImgDir',
            field=models.FilePathField(path='C:\\Users\\ernes\\Python\\fileDirs/users'),
        ),
    ]
