# Generated by Django 2.2 on 2020-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0010_auto_20200204_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='clipDir',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\ernes\\Python\\fileDirs/clips'),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='faceCaptureDir',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\ernes\\Python\\fileDirs/faceCaptures'),
        ),
    ]
