# Generated by Django 2.2 on 2020-02-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0014_auto_20200204_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifImgDir',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\ernes\\Python\\fileDirs/notifImg'),
        ),
    ]
